language: ruby
rvm:
  - 2.3.1

env:
  - DB:postgresql

script:
  # - RAILS-ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

services:
  - posgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
